### ISSUE TITLE
[texture] texture corruptions

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1194] opened 2022-02-24 14:59 UTC
Textures sometimes become slightly corrupted. I don't know how this happens yet. Maybe after playing the game for a while?

![image](https://cdn.discordapp.com/attachments/756287461830688810/946332026938724372/unknown.png)
![image](https://cdn.discordapp.com/attachments/756287461830688810/946333357602635796/unknown.png)
![image](https://cdn.discordapp.com/attachments/756287461830688810/946333357376167966/unknown.png)

**Comment by water111** [comment] 2022-02-25 01:13
For a long time I've thought that there's a race condition for the level tfrag textures (the `upload-now!` in `texture-page-near-allocate`).  I wonder if this is the cause?  In the real game, you'd only get this for exactly one frame (the first frame where an object with corrupted texture is used), but it's possible that our texture conversion cache could grab the bad version before it's fixed.

**Comment by water111** [comment] 2022-03-03 01:12
This should be fixed by https://github.com/open-goal/jak-project/pull/1212, which completely removed the texture cache and conversion process.

**Closed by water111** 2022-03-03 01:12 UTC
