### ISSUE TITLE
shrubbery has incorrect lighting at nighttime

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2418] opened 2023-03-26 00:35 UTC
![Image](https://user-images.githubusercontent.com/13153231/227748918-61f2a9b2-6a41-438f-b7ee-4d04cedcf027.png)

**Comment by water111** [comment] 2023-03-26 00:47
duplicate of https://github.com/open-goal/jak-project/issues/2419

**Closed by water111** 2023-03-26 00:47 UTC
