### ISSUE TITLE
SDL Error: gl_make_display failed

### ISSUE THREAD

**Issue by robehickman** [open-goal/jak-project#2744] opened 2023-06-18 18:23 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I have compiled and run opengoal previously on this computer with no issues. I just pulled the github repo and recompiled as I wanted to see how Jak2 progress is going. Howeaver now the game will not start with an SDL error. Other OpenGL stuff is running fine, and the previous version of opengoal was working fine a few mins earlier.

-------- CPU Information --------
 Brand: AuthenticAMD
 Model: AMD Ryzen 5 2600X Six-Core Processor           
 AVX  : true
 AVX2 : true
[34:10:800] [info] No project path provided, looking for data/ folder in current directory
[34:10:801] [info] Current executable directory - /home/a/jak-project/build/game/gk
[34:10:801] [info] Using development repo path: /home/a/jak-project
[34:10:801] [info] AVX2 mode disabled
[34:10:801] [info] OpenGOAL Runtime 1.0
[34:10:806] [info] GFX Init
[34:10:885] [info] SDL Initialized, compiled with version - 2.26.5 | linked with version - 2.26.5
[34:10:885] [info] gl init took 0.079s

[34:10:885] [error] SDL Error: gl_make_display failed - Could not create display window - Cause: SDL not configured with OpenGL/GLX support
[34:10:885] [error] Failed to make main display.
[34:10:885] [debug] [VM] Preparing...
[34:10:885] [debug] [VM] Prepared
[34:10:885] [debug] # Initialize IOP...

### How To Reproduce

Compile and run the game as per the readme.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Game should run and open an openGL window correctly.

### Operating System

Ubuntu 

### OpenGOAL Version

c41a66829f2a25fc43d07060b20aec47846875ac

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment] 2023-06-18 18:25
Clean CMake cache and try again?

**Comment by Hat-Kid** [comment] 2023-06-18 18:30
Try installing the `libgl1-mesa-dev` package with `apt`.

Since the switch to SDL, Fedora users need to add the `mesa-libGL-devel` package as a dependency to configure SDL with OpenGL support which I added to the readme, so I would assume this is the closest Ubuntu/Debian equivalent.

**Comment by xTVaser** [comment] 2023-06-18 18:35
I believe this would be the non-dev version https://packages.ubuntu.com/focal/libgl1-mesa-glx

**Comment by robehickman** [comment] 2023-06-18 18:57
Thanks, this computer is still running 21.04.  'libgl1-mesa-glx' is already installed. 'libgl1-mesa-dev' doesn't exist in the repo as far as I can see.

Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

**Comment by water111** [comment] 2023-06-18 23:00
`libgl1-mesa-dev` did exist: https://launchpad.net/ubuntu/hirsute/amd64/libgl1-mesa-dev/20.3.4-1 but 21.04 is end-of-life and you should probably upgrade. You could also try installing `mesa-common-dev` maybe.  

We recently switched from glfw to SDL2, which handles opengl a little bit differently.  This is how SDL2 figures out if you have opengl support or not: https://github.com/libsdl-org/SDL/blob/c6ee9780df4286f66c38f3fa9732daa9afe0a8a3/cmake/sdlchecks.cmake#L644, so you should find whatever package provides this header.

After installing the package you'll probably need to delete the build folder and run cmake again for it to re-run the check.

**Comment by robehickman** [comment] 2023-06-18 23:09
Neither of those packages seem to exist in the repository archive any more, so you're right that I should upgrade. It's not something I'm going to have time for for several weeks though as I need this computer working for important work stuff, and it's already working for that.

Would be worthwhile adding a check for this header to the cmake for opengoal so that it fails during build, instead of confusingly during runtime.

**Comment by xTVaser** [comment] 2023-06-18 23:19
Closing the issue as I believe the root cause has been identified, and the solution has worked for others.  Feel free to re-open if the solution doesn't work for you when you are able to update your distro.

And feel free to open a PR contributing a header check in the cmake, it would be very low priority since it only affects development environments, and the README discusses this requirement amongst others (but should probably be added to all distros, not just Fedora).

**Closed by xTVaser** 2023-06-18 23:19 UTC
Labels: bug

**Comment by robehickman** [comment] 2023-06-18 23:51
No problem, thank you for your help.

**Comment by robehickman** [comment] 2023-06-19 00:13
@xTVaser Do you know which commit was the last one using  glfw?

**Comment by xTVaser** [comment] 2023-06-19 00:15
https://github.com/open-goal/jak-project/commit/08741f0a427a568296411e6b6a51fc425ec048fa
