### ISSUE TITLE
Gun course sound breaks

### ISSUE THREAD

**Issue by bejt68** [open-goal/jak-project#3286] opened 2024-01-01 06:17 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When doing the gun courses (both scattergun and blaster), partway through the course the audio of certain things cuts out. These include gun sounds, targets popping up, targets breaking, score sounds, etc. Once they break, they might occasionally work again for a few shots, but most sounds were silenced for the remainder of the course.

### How To Reproduce

Do a gun course using either scattergun or blaster (haven't tested other weapons, haven't made it that far in the game yet).

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Sounds should go off when doing things.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13803649/opengoal-support-package.zip)

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment] 2024-01-01 13:37
"I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports"

Duplicate of #3285

**Closed by ManDude** 2024-01-01 13:37 UTC
Labels: bug, jak2
