### ISSUE TITLE
[decomp] poor handling of unreachable code after an infinite `while` loop

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#860] opened 2021-09-28 02:51 UTC
```lisp
(let ((f30-0 (if arg1
                1.0
                0.0
                )
         )
        )
   (while #t
    (set! f30-0 (seek f30-0 1.0 (* 0.2 (-> *display* seconds-per-frame))))
    (let ((a0-5 (-> self skel root-channel 0)))
     (set! (-> a0-5 param 0) f30-0)
     (joint-control-channel-group-eval!
      a0-5
      (the-as art-joint-anim #f)
      num-func-loop!
      )
     )
    (ja-post)
    (update! (-> self sound))
    (suspend)
    )
   )
  (the-as none enter-state)
...
```

This can be found in `village3-obs` - https://github.com/xTVaser/jak-project/tree/decomp/obs-files if it hasn't merged yet

**Comment by water111** [comment] 2022-02-17 02:45
duplicate of https://github.com/open-goal/jak-project/issues/329

**Closed by water111** 2022-02-17 02:45 UTC
Labels: decompiler
