### ISSUE TITLE
Game runs occassionally too fast

### ISSUE THREAD

**Issue by AlphaNERD-** [open-goal/jak-project#1555] opened 2022-06-25 19:00 UTC
Hello people,

So as the title says Jak can occassionally run too fast on one of my systems. This happens for example when i'm running under the rocks on the "border" between Sandover Village and Sentinel Beach.

Here's the data of my system affected by this issue:
GPD Win 2
Intel Core m3-7y30 (2 cores @ 1 GHz)
8 GB LPDDR3 RAM
Intel HD 615
Windows 10 Build 2004 (i think)

Of course my GPD Win 2 is not the strongest gaming system under the sun so it might be the same issue as this one after all: https://github.com/open-goal/jak-project/issues/1090

Another theory i have is that v-syncing may not work too well. I have Sims 2 and some other game installed on the GPD which didn't engage V-Sync.

**Comment by ManDude** [comment] 2022-06-25 19:03
What version are you running on? What framerate is your game set to? Can you turn on the frame time plot (top bar -> Windows -> Frame Time Plot) and see if the game is running at the target framerate?

**Comment by AlphaNERD-** [comment] 2022-06-27 19:57
Soooo, i test the game a bit. It turns out that the frametimes would exceed 20ms a lot when running around at sentinel beach or in the forbidden jungle. That's when the game starts running too fast.

I have tested it with OpenGOAL 0.1.9.

**Comment by ManDude** [comment] 2022-06-27 19:58
What framerate did you set the game to? Do you have a framerate setting anywhere?

**Comment by AlphaNERD-** [comment] 2022-06-27 20:00
I tested the game with the frame limiter disabled and enabled and the frame limiter didn't make a difference. The frame limiter war set to 60 fps.

**Comment by ManDude** [comment] 2022-06-27 20:03
I think this is just a duplicate of #1090 then.

**Closed by ManDude** 2022-06-27 20:03 UTC
