### ISSUE TITLE
health bar jak icons not centered

### ISSUE THREAD

**Issue by novaarby** [open-goal/jak-project#3221] opened 2023-11-25 08:53 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Apologies if this report is lacking in necessary info. It's my first time reporting bugs, but I really want to help you guys out if I am able, as a huge Jak fan.

When playing through the beginning, I noticed that in dead town, that normal jak's icon over the health bar is uncentered and on the right side, while dark jak's was the same, but on the left.

my resolution is 3440x1440, and may have something to do with that. Seems to happen both on fullscreen, windowed, and borderless.
**_However_**
Once I turn the windowed version small and back to roughly a square window at a very small size, it seems to be fine. It appears to be a scaling issue.

![normalhead](https://github.com/open-goal/jak-project/assets/151994607/8da2d632-2562-4dcc-8967-d9bff12f40db)
![darkjakhead](https://github.com/open-goal/jak-project/assets/151994607/54f6275b-7ae5-4311-9744-9ae91da1b1e0)
![darkjaksmallwindow](https://github.com/open-goal/jak-project/assets/151994607/759165fa-5f85-4ab2-86cf-f30a50141cc3)
![smallwindowicon](https://github.com/open-goal/jak-project/assets/151994607/bb81046c-630d-4232-b8f7-c24f102f7edb)

### How To Reproduce

3440x1440 scaling
60fps

Wanted to try operating in different aspect ratios, but I don't have enough time. Wanted to get this out there that it's happening to me.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Icons should be centered and supported by ultrawide monitors. Unsure if isolated issue.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13463406/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment] 2023-11-25 09:20
duplicate of #2486

**Closed by Zedb0T** 2023-11-25 09:20 UTC
Labels: bug, jak2
