### ISSUE TITLE
[Settings] Save audio volume settings

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#1686] opened 2022-07-20 00:08 UTC
### What feature is your idea related to?

More settings persistence

### Describe the solution you'd like.

Saving out the chosen volume levels in the game settings to the settings file so that they can be retained between reboots

**Comment by Zedb0T** [comment] 2022-07-20 00:10
In the normal game, the sound settings are saved to the memory card and that is also the case here. If you adjust the in game settings then save the game, when you load it it will adjust automatically.

If you want it to persist globally you can adjust the volume in volume mixer if you are on windows and it should stay constant from boot there.

**Comment by BreakPoints** [comment] 2022-07-20 00:22
Ah, you're right. I've been jumping between saves a lot.

There aren't many cases where you'd want different volume settings per save. I suppose it worked that way to account for people sharing a console and having different preferences. Not sure if the change of logic is worth it at this stage.

**Comment by xTVaser** [comment] 2023-04-08 20:06
It would be a fairly easy change to move some settings into `pc-settings` instead of the memory card.  Early on this was decided against, so closing assuming that decision still holds true -- this is working as intended (sound settings and most original settings are handled by the memory card)

**Closed by xTVaser** 2023-04-08 20:06 UTC
Labels: enhancement
