### ISSUE TITLE
Black screen when launching

### ISSUE THREAD

**Issue by FreakinEh** [open-goal/jak-project#3279] opened 2023-12-31 04:47 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

when i launch the game it boots, i get all the sounds from the game but no picture, but when i launch in debug mode it works perfect, any suggestions

### How To Reproduce

when i launch the game it boots, i get all the sounds from the game but no picture, but when i launch in debug mode it works perfect, any suggestions

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

when i launch the game it boots, i get all the sounds from the game but no picture, but when i launch in debug mode it works perfect, any suggestions

### Environment Information

CPU i9 9900K GPU 4070 Windows 10 open goal version 4.0

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by FreakinEh** [comment] 2023-12-31 04:52
[
![Capture](https://github.com/open-goal/jak-project/assets/155282621/daafd9c9-c077-49b6-b8cf-e255771ef1fa)
](url)

**Comment by dallmeyer** [comment] 2024-01-17 01:55
Consistent way to reproduce:

- monitor setup: I have "monitor 0" on the right, and "monitor 1" on the left
- Boot the game in windowed mode on "monitor 0", no issues
- Drag the window over to "monitor 1" so it updates display-settings.json (`xpos` should end up negative)
- Reboot in debug mode or close/reopen, and it should get stuck on black screen on "monitor 1"

**Comment by Zedb0T** [comment] 2024-01-17 02:43
User Minecraft Steve was running into this issue and was open to testing out any potential fixes if they got deployed
https://discord.com/channels/756287461377703987/1182090440141447211/1182107505178988635

**Comment by xTVaser** [comment] 2024-01-17 03:18
Repro doesn't work for me, the negative coordinates are expected (global screen coordinates).  The window opens as expected on the other monitor where it was previously positioned.

The only problem I saw was related to the pc-settings not behaving as I would intuitively expect (the game defaulting to windowed mode now, despite that not being the default).  But this isn't exactly a new pain-point and didn't result in any unusable problems (like the screen being black). This seems to happen because there is no call to `set_window_display_mode` on initial boot if there is no pc-settings file.

**Comment by dallmeyer** [comment] 2024-03-03 03:54
https://github.com/glfw/glfw/issues/1682#issuecomment-1000415848

^ For me, killing Nahimic services from Task Manager fixed this issue

**Comment by xTVaser** [comment] 2024-05-26 20:19
I'm going to close this, not only have we not heard any reports of this issue in months, but it was traced back (in this situation) to being completely unrelated to opengoal/sdl/etc.

**Closed by xTVaser** 2024-05-26 20:19 UTC
Labels: bug, jak2

**Comment by ItsModern** [comment] 2024-06-23 04:41
Its happening to me too! That guy closed it even though its not fixed...

**Comment by tliron** [comment] 2024-08-01 19:29
Sorry, but I am experiencing a black screen even though Nahimic service is disabled. Happy to help debug this.

My setup: AMD 5800X3D, NVIDIA RTX 4090, Windows 11, 4K TV.

**Comment by xTVaser** [comment] 2024-08-01 19:50
@tliron If you are in the discord you can follow this conversation where I'm testing changes https://discord.com/channels/756287461377703987/1266995279232634971/1268407646440914964

If not, if your logs have the same thing mentioned here, you are likely in the same boat (the game is selecting the wrong resolution to use) https://github.com/open-goal/jak-project/issues/3563#issuecomment-2184527575

**Comment by tliron** [comment] 2024-08-01 20:09
Thanks, but I do not have the `pc-settings.gc` file in the Jak 1 settings folder. I have only `display-settings.json` and `input-settings.json`.

**Comment by xTVaser** [comment] 2024-08-01 21:00
I would check for the log I referenced, one of the other problems is that the `pc-settings.gc` file is not saved until you modify it.  

That and the bug will be addressed here https://github.com/open-goal/jak-project/pull/3624

Here's a default settings file you could drop-in, in the meantime.

[pc-settings.zip](https://github.com/user-attachments/files/16461863/pc-settings.zip)

**Comment by tliron** [comment] 2024-08-01 23:18
Still doesn't work. Sorry, I'm not on Discord, I hope it's OK to discuss here. I put the `pc-settings.gc` in the zip into the settings folder, next to the other files mentioned above. I tried editing to `(game-size 2840 2160)` in it. Still black screen on startup.

**Comment by tliron** [comment] 2024-08-01 23:21
Attaching my latest log: [jak1.2024-08-01T18-20-19.log](https://github.com/user-attachments/files/16462684/jak1.2024-08-01T18-20-19.log)

**Comment by xTVaser** [comment] 2024-08-01 23:27
> [end] OpenGL error 0x502 S8246 T824C: GL_INVALID_OPERATION error generated. Source and destination dimensions must be identical with the current filtering modes.

It seems to be the same issue, so hopefully when that fix is released at the end of the month it resolves the problem for you.

From your logs i also see

```
[PC] PC Settings found at 'C:\Users\emble\AppData\Roaming\OpenGOAL\jak1\settings/pc-settings.gc'...loading!
****** CALL TO kopen() ******
[20:20] [warn] [DISPLAY] 2840x2160 is not a supported resolution
[PC Settings]: Invalid game-size resolution 2840 x 2160, defaulting to 1536 x 864
```

Are you sure you don't mean to use 3840 x 2160 (actual 4k?) 2840x2160 is a very odd resolution. `defaulting to 1536 x 864` implies this is the resolution that SDL thinks your monitor is already set to?  Are you using a non-100% display scaling?

**Comment by tliron** [comment] 2024-08-01 23:36
LOL, that was a typo, thank you for paying attention. :) Switching to correct resolution allows the game to finally start, thanks!
