### ISSUE TITLE
inverted first person camera doesn't seems to work for Jak 2

### ISSUE THREAD

**Issue by Gitaroo326** [open-goal/jak-project#3179] opened 2023-11-08 05:48 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

the option toggle doesn't seems to apply, using a dualsense controller

### How To Reproduce

first person camera is always inverted

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

the first person camera is always inverted regardless of any option I picked in the camera menu

### Environment Information

win 11
12700k
4080

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by dallmeyer** [comment] 2023-11-08 05:51
dupe of #3116 / see #3167

**Closed by dallmeyer** 2023-11-08 05:51 UTC
Labels: bug, jak2
