### ISSUE TITLE
mars tomb door lasers point at origin

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2538] opened 2023-04-24 01:10 UTC
![image](https://user-images.githubusercontent.com/7569514/233878140-1ddd3a02-d3f0-41a7-b4a5-27656c81d809.png)

**Comment by ManDude** [comment] 2023-04-24 01:13
![image](https://user-images.githubusercontent.com/7569514/233878351-d109014c-3a20-43cf-b464-a24489e34eb6.png)

Points at origin. Possibly related to #2477

**Comment by water111** [comment] 2023-06-04 21:40
This is caused by `vf0` being clobbered in `(defstate active (tomb-sphinx)`.

In OpenGOAL, all vf's are clobbered on suspend. This matches the original game, with the exception of `vf0`, which is a hardware constant on the real PS2.

Maybe this is a sign we should treat `vf0` differently, as this problem shows up in a few other places and seems like it should be fixed properly.

That said, I don't have any good ideas yet (excluding ones where we reload the register on each use).

**Comment by water111** [comment] 2023-06-05 22:41
I couldn't figure out a good fix so I just patched this in the ~3 places it could be a problem (it's easy to find at least). Not ideal, but I think it's ok.

**Comment by water111** [comment] 2023-06-06 23:07
fixed in https://github.com/open-goal/jak-project/pull/2692

**Closed by water111** 2023-06-06 23:07 UTC
Labels: bug, game, jak2
