### ISSUE TITLE
[build] set up dependencies for code files properly

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1126] opened 2022-02-03 04:10 UTC
we've been pretty lazy with this since it's not really blocking anything but it would be nice to set this up to speed up build times a bit, no reason an edit to `default-menu` should build the entire game.

**Comment by xTVaser** [comment] 2023-04-18 04:11
Duplicate of https://github.com/open-goal/jak-project/issues/1353

**Closed by xTVaser** 2023-04-18 04:11 UTC
