### ISSUE TITLE
[Setup] Installing Jak and Daxter in different locations other than "C:\Users\{username}\Appdata\Roaming"

### ISSUE THREAD

**Issue by YungMoniCA1** [open-goal/jak-project#1743] opened 2022-08-07 23:07 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I personally have the OpenGoal project and installer located in the following drive and path "D:\Naughty Dog\*" (yes I know, it is a personal preference). However, whenever I want to decompile/compile or setup the game it installs in my "appdata" folder (highly dislikable feature lol). Other than attempting to create symlinks to the data folder in "appdata" to reflect into the data folder in my current directory may we suggest that the decompile/compile or setup remains in the directory in which the setup is installed (i.e E:\Naughty Dog\OpenGOAL-Launcher\data\*)?

### How To Reproduce

Run the latest installer 1.0.0. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

suggest that the decompile/compile or setup remains in the directory in which the setup is installed (i.e E:\Naughty Dog\OpenGOAL-Launcher\data\*)

### Operating System

Windows 10 21H2

### OpenGOAL Version

 1.0.0

### Game Version

NTSC Greatest Hits version (red label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by xTVaser** [comment] 2022-08-08 00:04
Not applicable to this repo and a duplicate of these issues:
- https://github.com/open-goal/launcher/issues/130
- https://github.com/open-goal/launcher/issues/129

**Closed by xTVaser** 2022-08-08 00:04 UTC
Labels: bug
