### ISSUE TITLE
'A' button permanently triggers pause menu on Xbox One controller; can't jump

### ISSUE THREAD

**Issue by Hendo16** [open-goal/jak-project#3115] opened 2023-11-02 12:28 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

As soon as I got control of Jak, I immediately tried jumping. The animation plays for a split second but then the pause menu appears. I checked the controller bindings and they were mapped just fine. Using the space button on my keyboard lets him jump, so I went back to the controller bindings and made the playstation 'X' button bind to the right shoulder button, so 'A' shouldn't do anything. Doing this, the right button now lets me jump just fine but 'A' triggers the pause menu just like my start button.

### How To Reproduce

1. Connect an Xbox One controller
2. Boot up Jak II
3. Start a New Game
4. Watch the cinematics
5. Once you gain control, attempt to jump using the jump button ('A')
6. Re-bind the playstation 'X' button to something else on the controller to test the xbox 'A' binding
7. Press 'A'

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Pressing A should have had Jak jump without triggering the pause menu

### Environment Information

CPU: Ryzen 3700x
GPU: RTX 3080 10GB
OS: Win 11
OpenGOAL:
- Launcher: v2.3.0
- Tooling: v0.1.44

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by Hat-Kid** [comment] 2023-11-02 12:31
The problem is most likely Steam Input interfering with the game's default input. You will have to either add the launcher/game to Steam or close Steam/disable the controller in the settings.

**Comment by ManDude** [comment] 2023-11-04 11:18
duplicate of like 10 other issues

**Closed by ManDude** 2023-11-04 11:18 UTC
Labels: bug, jak2
