### ISSUE TITLE
SDL Regression - Wrong Fullscreen Resolution Chosen at High DPI

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#2699] opened 2023-06-06 19:39 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Since the SDL changes, swapping to fullscreen mode with a non 100% scale set in Windows results in the wrong resolution being chosen.

From what I can see the desktop is forced into 100% scaling and a set resolution when fullscreening but if scaling was **not** set to 100% before swapping modes an incorrect desktop resolution is set. This means running at native resolution from the games settings still looks blurry.

Notes: Different scaling levels in Windows will lead to different incorrect desktop resolutions set, 2560x1600 125% ends up in a 4:3 resolution.

### How To Reproduce

- Set Windows display scaling to a non 100% value
- Boot game and set display mode to fullscreen
- Dev topbar is a good reference to check resolution as it does not scale

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

Native display resolution is selected for fullscreen

### Operating System

Windows 11 22H2

### OpenGOAL Version

dev

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by xTVaser** [comment] 2023-06-09 18:59
@BreakPoints Let me know if this works better https://github.com/open-goal/jak-project/pull/2713 as for ImGUI being blurry, I think that is expected as you have to do a bunch of other work to get that right, and it's probably not worth it since it's just for debugging - https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application

But I was able to reproduce the imgui bar not spanning the entire width, as well as the resolution clearly being wrong when you attempt to minimize the game (indication that the fullscreen window size was too small (25% scaled down for example).  Both of those are now fixed on my end.

**Comment by BreakPoints** [comment] 2023-06-10 00:57
Tried #2713 and it's an improvement, the Windows Desktop is now kept at native resolution.

The ImGUI being blurry is still being caused by the same issue as the rest of the game. On your PR the framebuffer of the game + ImGUI is being chosen based off of Windows scaling so on my 2560x1600 screen with 200% scaling I get a sharp 800p integer scaled image. With 150% scale we are now at an uneven scale so bilinear scaling is used from 1200p and that's when the whole image looks blurry.

In game resolution is scaled to this incorrect intermediate resolution, then scaled again to the desktop resolution Windows is running in. Same in fullscreen and borderless modes.

Windowed mode allows Windows scaling to scale up whatever game resolution is chosen, any resolution over 800p at 200% scaling is progressively more offscreen.

**Comment by ManDude** [comment] 2023-06-10 00:58
Can you post screenshots? So the problem is easier to visualize.

**Comment by BreakPoints** [comment] 2023-06-10 01:14
So it looks like currently things are being handled correctly but my problem is Windows needs to be told to not scale the window in order to play at resolutions higher than the scale would allow.

Windows at 200% scale:
![200% Zoom](https://github.com/open-goal/jak-project/assets/11966090/37093999-91ed-4766-a796-b7b1baea55a2)


Windows at 150% scale:
![150% Zoom](https://github.com/open-goal/jak-project/assets/11966090/4456e714-2aa2-4ab7-8a0b-532318738183)


Windows at 100% looks normal but for some reason I am unable to take Windows snip or Gamebar screenshots of either fullscreen or boarderless at this scale. I get black or stale frames.

**Comment by xTVaser** [comment] 2023-06-10 01:32
I really have no idea how this stuff is supposed to be handled properly and I couldn't find a consistent reference for how it's supposed to be done either.  In my linked PR I reference some SDL hints related to windows DPI awareness that may help (some solutions referenced this, I saw absolutely no difference using them).

I'll leave this to someone who has more of a clue than me.

I can also reproduce snipping tools problems / sometimes the borderless window doesn't want to minimize as gracefully as it should -- but I believe this is unrelated to scaling and is a separate issue.

**Comment by BreakPoints** [comment] 2023-06-10 01:51
I think it would be a flag that needs to be set that tells Windows that the application handles scaling itself. Forcing it in the compatibility settings results in native resolutions while scaling is enabled in Windows:
![image](https://github.com/open-goal/jak-project/assets/11966090/b0e4d030-1880-424e-a47a-a913ef25b8c0)

I'll have a dig but at least with #2713 and the above setting the issue can be worked around.

**Comment by ManDude** [comment] 2023-06-10 03:22
Just wondering - is this with MSAA on? Does this act differently with MSAA off in windowed mode?

**Comment by BreakPoints** [comment] 2023-06-10 12:32
This is all with MSAA off, windowed mode just increases the size of the windows by the display scaling percentage still leading to blurry images

**Closed** 2023-06-14 01:45 UTC
Labels: bug
