### ISSUE TITLE
Macro for when a function/method accesses the clock from `s6` without having to make it a behavior

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1910] opened 2022-09-24 18:45 UTC
If this is just looking at process clocks, I want to eventually turn this into a macro that doesn't require making things a behavior.

_Originally posted by @water111 in https://github.com/open-goal/jak-project/pull/1901#discussion_r979273390_

**Comment by ManDude** [comment] 2022-09-24 18:48
me too.

**Comment by ManDude** [comment] 2022-09-27 18:51
duplicate of #1872

**Closed by ManDude** 2022-09-27 18:51 UTC
Labels: decompiler, jak2
