### ISSUE TITLE
Krew’s reflection has no facial animation

### ISSUE THREAD

**Issue by PhantumJak** [open-goal/jak-project#3202] opened 2023-11-14 22:26 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

In the cutscene talking with Krew immediately after finishing the mission where you meet Brutter (the talking Lurker), Krew has a scene where he’s talking while looking at himself in the mirror. Krew’s reflection has a blank inanimate expression, no mouth movement or anything, while he is clearly talking and his “real” face can be seen with movement.

I believe this cutscene is where he asks Jak & Daxter to recover a lost statue of Mar from the sewers.

### How To Reproduce

Obviously the scene only happens once, BUT, can be reproduced by Replaying the Cutscene once you’ve unlocked Cutscene replay via the “Secrets” menu.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Krew’s reflection’s face/mouth should be moving while he talks.

### Environment Information

OpenGOAL v 0.2.2 on Steam Deck via Game Mode (using the shortcut command to play without opening OpenGOAL launcher)

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment] 2023-11-14 22:26
Duplicate of #2736

**Closed by ManDude** 2023-11-14 22:26 UTC
Labels: bug, jak2
