### ISSUE TITLE
Timeout detection and recovery on AMD RX Vega 64

### ISSUE THREAD

**Issue by dante3732** [open-goal/jak-project#1457] opened 2022-06-16 17:23 UTC
In random places of the game causes TDR.
Windows 11 Pro x64 21H2
AMD Ryzen 5 3600 4.2 Ghz
MSI Radeon VEGA 64 8 Gb HBM2 
2x8 Gb DDR4 3200

**Comment by water111** [comment] 2022-06-16 22:28
Do you mind trying with this option enabled?  This menu can be opened from the top menu bar, in Windows, Render Debug
![image](https://user-images.githubusercontent.com/48171810/174188757-6eb632df-2d7f-44a8-a420-73e4befcfac5.png)

**Comment by dante3732** [comment] 2022-06-17 08:19
> Do you mind trying with this option enabled? This menu can be opened from the top menu bar, in Windows, Render Debug ![image](https://user-images.githubusercontent.com/48171810/174188757-6eb632df-2d7f-44a8-a420-73e4befcfac5.png)

I complete 1 area and i think it fixed issue.

**Comment by xTVaser** [comment] 2022-06-30 02:41
Further info - Someone else had this issue on a vega 56 card as well.

**Comment by water111** [comment] 2022-07-16 00:37
duplicate of https://github.com/open-goal/jak-project/issues/1577, which might also be fixed now. Please let us know if this issue continues to happen on the latest version.

**Closed by water111** 2022-07-16 00:37 UTC
