### ISSUE TITLE
(Jak 1) Credits don't look right

### ISSUE THREAD

**Issue by ZippyZolton** [open-goal/jak-project#2840] opened 2023-07-23 23:42 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

https://github.com/open-goal/jak-project/assets/28773304/8905e081-0626-4e52-8513-cce1c1735cc3
There is a black 4:3 box that flickers a lot, this may be an issue with high frame rate. You can also see the level geometry on the left and Jak behind the box, which I don't think is intentional.

### How To Reproduce

View the credits at 16:9 and running at 150 fps

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

https://youtu.be/J56g-ULzfBQ

### Operating System

Windows 10 Pro

### OpenGOAL Version

v0.1.38

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by xTVaser** [comment] 2023-07-24 00:05
Likely a duplicate of https://github.com/open-goal/jak-project/issues/1521 The flickering was described as fixed as of 0.1.12, could be a recent regression.

**Comment by ZippyZolton** [comment] 2023-07-24 01:02
oh sorry, when trying to search for issues similar to this I specifically searched "credits" and "flashing" so I wouldn't have gotten it. As far as flickering goes, this is the only time I've beaten the game on OpenGOAL, so I also wouldn't have the experience from previous versions to see if it was regressed or always there, high fps or not.

**Comment by Margen67** [comment] 2023-08-05 14:56
This doesn't occur at 60 FPS.

**Comment by xTVaser** [comment] 2024-03-09 19:58
Closing as a duplicate

**Closed by xTVaser** 2024-03-09 19:58 UTC
Labels: bug, duplicate
