### ISSUE TITLE
game crashes during haven forest flying metalhead hoverboard chase, unless played in debug mode

### ISSUE THREAD

**Issue by legendddhgf** [open-goal/jak-project#3559] opened 2024-06-20 03:34 UTC
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

This usually happens when I am about to capture a flying metalhead. Sometimes I capture one, sometimes 2 or 3 before it hits. This has happened every single time I tried to play this level and simply cannot progress at this point because the game just abruptly crashes every time.

### How To Reproduce

Play through Haven forest flying metalhead hoverboard level. I'm not sure if extra tricks during play make this more or less reproducible.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The game shouldn't crash and close.

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/15908090/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by legendddhgf** [comment] 2024-06-20 03:46
Additional notes:

I eventually tried nuking my settings and then uninstalling / reinstalling the game. The same issue continued to happen.

However, in debug mode, I was able to complete the level without issue
during debug mode, I saw the following task manager messages start to come up, with timing around when I would've instead expected the game to crash:
![image](https://github.com/open-goal/jak-project/assets/10329638/01c370a2-3d6c-4c63-9f05-f630b224a144)

I also saw some red text come up for moments, but I didn't have the time to register what was displayed or take a screenshot of them.

**Comment by xTVaser** [comment] 2024-07-30 05:20
> [24:41] [die] Assertion failed: 'offset + 16 == transfer.size_bytes'
	Source: D:/a/jak-project/jak-project/game/graphics/opengl_renderer/foreground/Shadow2.cpp:158
	Function: virtual void __cdecl Shadow2::render(DmaFollower &, SharedRenderState *, ScopedProfilerNode &)

This is a duplicate of https://github.com/open-goal/jak-project/issues/3009 from the looks of it

**Closed by xTVaser** 2024-07-30 05:20 UTC
Labels: bug, jak2
