### ISSUE TITLE
decompiler: automatic stack casts don't seem to take sizing into account

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1825] opened 2022-08-30 04:19 UTC
```mips
    daddiu gp, sp, 64         ;; [ 59] (set! gp-2 (+ sp-0 64)) [sp: <uninitialized> ] -> [gp: vector ]
    mtc1 f0, r0               ;; [ 60] (set! f0-4 0) [] -> []
    lui v1, 16256             ;; [ 61] (set! v1-10 1.0) [] -> [v1: float ]
    mtc1 f30, v1              ;; [ 62] (set! f30-0 (gpr->fpr v1-10)) [v1: float ] -> []
    daddiu s5, gp, 224        ;; [ 63] (set! s5-0 (+ gp-2 224)) [gp: vector ] -> [s5: <uninitialized> ]
    daddiu s4, sp, 608        ;; [ 64] (set! s4-0 (+ sp-0 608)) [sp: <uninitialized> ] -> [s4: vector ]
```
For example, here it automatically makes offset `64` a `vector`, when it is more likely something like a `collide-query` as it takes up far more than just `16` bytes.  `vector` should be disqualified as an option (i think?) and be forced to be a manual addition

**Comment by water111** [comment] 2022-08-30 04:30
kinda related https://github.com/open-goal/jak-project/issues/724
i do have some stuff in progress that would throw an error/warning in this case because the gaps in the stack layout.

We could also have some default guesses for specific sizes, I'd guess that `collide-query` is the only common stack type with exactly this size, for example.

**Comment by water111** [comment] 2022-10-16 20:31
duplicate of https://github.com/open-goal/jak-project/issues/724

**Closed by water111** 2022-10-16 20:31 UTC
Labels: decompiler
